//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.239
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lol_Starter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WowPath {
            get {
                return ((string)(this["WowPath"]));
            }
            set {
                this["WowPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>set realmlist LandOfLegends.de</string>
  <string>set realmlist server2.landoflegends.de:3850</string>
  <string>set realmlist 89.163.172.253:3800</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RealmList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RealmList"]));
            }
            set {
                this["RealmList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Land Of Legends 3.3.5a</string>
  <string>Land Of Legends DEV</string>
  <string>Land Of Legends Vanilla</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RealmName {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RealmName"]));
            }
            set {
                this["RealmName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WDBDelete {
            get {
                return ((bool)(this["WDBDelete"]));
            }
            set {
                this["WDBDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WTFDelete {
            get {
                return ((bool)(this["WTFDelete"]));
            }
            set {
                this["WTFDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StarterClose {
            get {
                return ((bool)(this["StarterClose"]));
            }
            set {
                this["StarterClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayRadioOnStart {
            get {
                return ((bool)(this["PlayRadioOnStart"]));
            }
            set {
                this["PlayRadioOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://matrix-webdesigner.de/stream-box/playlist.php?s=89.163.172.250&p=8700&t=as" +
            "x")]
        public string RadioPath {
            get {
                return ((string)(this["RadioPath"]));
            }
            set {
                this["RadioPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int RadioVolume {
            get {
                return ((int)(this["RadioVolume"]));
            }
            set {
                this["RadioVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VoteReminding {
            get {
                return ((bool)(this["VoteReminding"]));
            }
            set {
                this["VoteReminding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BrowserActiv {
            get {
                return ((bool)(this["BrowserActiv"]));
            }
            set {
                this["BrowserActiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int NewsEntrysCount {
            get {
                return ((int)(this["NewsEntrysCount"]));
            }
            set {
                this["NewsEntrysCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Meine Allianz Gilde")]
        public string AllianceGuildName {
            get {
                return ((string)(this["AllianceGuildName"]));
            }
            set {
                this["AllianceGuildName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.landoflegends.de/viewforum.php?f=64")]
        public string AllianceGuildLink {
            get {
                return ((string)(this["AllianceGuildLink"]));
            }
            set {
                this["AllianceGuildLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Meine Horde Gilde")]
        public string HordeGuildName {
            get {
                return ((string)(this["HordeGuildName"]));
            }
            set {
                this["HordeGuildName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.landoflegends.de/viewforum.php?f=64")]
        public string HordeGuildLink {
            get {
                return ((string)(this["HordeGuildLink"]));
            }
            set {
                this["HordeGuildLink"] = value;
            }
        }
    }
}
